import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import BrandFacehash from "@/components/BrandFacehash";
import GlobalDock from "@/components/GlobalDock";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <BrandFacehash />
        {children}
        <GlobalDock />
        <Analytics />
      </body>
    </html>
  );
}
